/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/VtKqM7RBnQi
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { APP_NAME, DISCORD_URL, GITHUB_URL, TELEGRAM_URL, TWITTER_URL } from "@/constants"
import Link from "next/link"
import { DiscordIcon, GitBookIcon, TelegramIcon } from "./icons"
import { TwitterIcon } from "lucide-react"

export function Footer() {
  return (
    <footer className="bg-gray-900 text-gray-400 py-8 sm:py-12">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 flex flex-col sm:flex-row justify-between items-center">
        <div className="text-sm">&copy; 2024 {APP_NAME}. All rights reserved.</div>
        <div className="flex items-center space-x-4 mt-4 sm:mt-0">
          <Link href={TWITTER_URL} className="hover:text-gray-200 transition-colors" prefetch={false}>
            <TwitterIcon className="h-5 w-5" />
            <span className="sr-only">Twitter</span>
          </Link>
          <Link href={TELEGRAM_URL} className="hover:text-gray-200 transition-colors" prefetch={false}>
            {/* <SignalIcon className="h-5 w-5" /> */}
            <TelegramIcon className="h-5 w-5" />
            <span className="sr-only">Telegram</span>
          </Link>
          <Link href={DISCORD_URL} className="hover:text-gray-200 transition-colors" prefetch={false}>
            <DiscordIcon className="h-5 w-5" />
            <span className="sr-only">Discord</span>
          </Link>
          <Link href={GITHUB_URL} className="hover:text-gray-200 transition-colors" prefetch={false}>
            {/* <GitlabIcon className="h-5 w-5" /> */}
            <GitBookIcon className="h-5 w-5" />
            <span className="sr-only">Gitbook</span>
          </Link>
        </div>
      </div>
    </footer>
  )
}

