/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/1fVuszaOgd3
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";

import { useState } from "react";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  CardFooter,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { CheckIcon } from "lucide-react";
import { WinnersPodium } from "./winners-podium";
import { WinnersPodiumOverall } from "./winners-podium-overall";
import { WinnersPodiumBooth } from "./winners-podium-booth";
import { WinnersPodiumSwag } from "./winners-podium-swag";

export function WinnersTabBox() {
  const [activeTab, setActiveTab] = useState("Overall");
  return (
    <div className="w-full max-w-screen-lg mx-auto sm:px-4 md:px-8">
      <Tabs value={activeTab} onValueChange={setActiveTab} className="border-b">
        <TabsList className="flex flex-shrink mx-auto">
          <TabsTrigger value={"Overall"}>Overall</TabsTrigger>
          <TabsTrigger value={"Booth"}>Booth</TabsTrigger>
          <TabsTrigger value={"Swag"}>Swag</TabsTrigger>
          <TabsTrigger value={"Sustainable"}>Sustainable</TabsTrigger>
        </TabsList>
        <TabsContent value={"Overall"}>
          <Card className="p-6">
            <CardHeader>
              <CardTitle>Best Overall</CardTitle>
              <CardDescription>
                Sponsor with the top overall Swagathon score based on the
                transparent rating formula.
              </CardDescription>
              <CardContent>
                <WinnersPodiumOverall />
              </CardContent>
            </CardHeader>
          </Card>
        </TabsContent>
        <TabsContent value={"Booth"}>
          <Card className="p-6">
            <CardHeader>
              <CardTitle>Best Booth</CardTitle>
              <CardDescription>
                Sponsor with the most awesome booth! The booth with the highest
              </CardDescription>
            </CardHeader>
            <CardContent>
              <WinnersPodiumBooth />
            </CardContent>
          </Card>
        </TabsContent>
        <TabsContent value={"Swag"}>
          <Card className="p-6">
            <CardHeader>
              <CardTitle>Best Swag</CardTitle>
              <CardDescription>
                These are the sponsors with the best swag based on the
              </CardDescription>
            </CardHeader>
            <CardContent>
              <WinnersPodiumSwag />
            </CardContent>
          </Card>
        </TabsContent>
        <TabsContent value={"Sustainable"}>
          <Card className="p-6">
            <CardHeader>
              <CardTitle>Get in Touch</CardTitle>
              <CardDescription>
                Have questions or need help? Contact us.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <form className="grid gap-4">
                <div className="grid gap-1">
                  <Label htmlFor="name">Name</Label>
                  <Input id="name" placeholder="Your name" />
                </div>
                <div className="grid gap-1">
                  <Label htmlFor="email">Email</Label>
                  <Input id="email" type="email" placeholder="Your email" />
                </div>
                <div className="grid gap-1">
                  <Label htmlFor="message">Message</Label>
                  <Textarea id="message" placeholder="Your message" rows={4} />
                </div>
                <Button type="submit">Submit</Button>
              </form>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}
