/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0bcc4osjgY1
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import Link from "next/link";
import {
  TooltipProvider,
  Tooltip,
  TooltipTrigger,
  TooltipContent,
} from "@/components/ui/tooltip";
import { Card } from "../ui/card";
import { InfoIcon } from "lucide-react";
import { useEffect, useState } from "react";

interface Sponsor {
  id: number;
  name: string;
  booth: string | null;
  website: string;
  image_thumb: string;
  swag: boolean;
  num1: number;
  num2: number;
  num3: number;
  num4: number;
  num5: number;
  overallScore: number;
  [key: string]: any; // Add index signature
}

export function WinnersPodiumBooth() {
  const [loading, setLoading] = useState(true);
  const [sponsors, setSponsors] = useState<Array<Sponsor>>([]);


  useEffect(() => {
    const fetchSponsors = async () => {
      setLoading(true);
      try {
        const response = await fetch("/api/sponsors");
        const data = await response.json();
        if (!response.ok) {
          throw new Error(data?.message || "Failed to fetch sponsors");
        }
        // sort sponsors array by num1 property
        // and only keep the top 10
        data.sort((a: Sponsor, b: Sponsor) => b.num1 - a.num1);
        const top10sponsors = data.slice(0, 10);
        setSponsors(top10sponsors);
      } catch (error) {
        console.error("Error fetching sponsors:", error);
      } finally {
        setLoading(false);
      }
    };
    fetchSponsors();
  }, []);


  return (
    <div className="flex flex-col items-center">
      <div className="flex justify-center items-end space-x-4 mt-8">
        <div className="flex flex-col items-center">
          <img
            src={sponsors[1]?.image_thumb}
            alt="2nd place logo"
            className="mb-2 rounded-lg  w-44 border-4 border-[#0077b6]"
          />
          <div className="w-60 h-36 bg-[#0077b6] flex items-center justify-center rounded-lg relative">
            <span className="text-white text-lg font-bold">
              2<sup>nd</sup>
            </span>
            <div className="absolute top-0 right-0 bg-gray-900 text-white px-2 py-0.5 rounded-full text-xs font-medium">
              Score: {sponsors[1]?.overallScore}
            </div>
          </div>
          <div className="mt-2 flex items-center">
            <Link
              href="#"
              className="text-sm font-medium hover:underline"
              prefetch={false}
            >
              {sponsors[1]?.name}
            </Link>
            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  <button className="ml-2 text-gray-500 hover:text-gray-900 dark:hover:text-gray-100">
                    <InfoIcon className="h-4 w-4" />
                  </button>
                </TooltipTrigger>
                <TooltipContent>
                  <p>{sponsors[1]?.description}</p>
                </TooltipContent>
              </Tooltip>
            </TooltipProvider>
          </div>
        </div>
        <div className="flex flex-col items-center">
          <img
            src={sponsors[0]?.image_thumb}
            alt="1st place logo"
            className="mb-2 rounded-lg w-56 border-4 border-[#023e8a]"
          />
          <div className="w-64 h-48 bg-[#023e8a] flex items-center justify-center rounded-lg relative">
            <span className="text-white text-lg font-bold">
              1<sup>st</sup>
            </span>
            <div className="absolute top-0 right-0 bg-gray-900 text-white px-2 py-0.5 rounded-full text-xs font-medium">
              Score: {sponsors[0]?.overallScore}
            </div>
          </div>
          <div className="mt-2 flex items-center">
            <Link
              href="#"
              className="text-sm font-medium hover:underline"
              prefetch={false}
            >
              {sponsors[0]?.name}
            </Link>
            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  <button className="ml-2 text-gray-500 hover:text-gray-900 dark:hover:text-gray-100">
                    <InfoIcon className="h-4 w-4" />
                  </button>
                </TooltipTrigger>
                <TooltipContent>
                  <p>{sponsors[0]?.description}</p>
                </TooltipContent>
              </Tooltip>
            </TooltipProvider>
          </div>
        </div>
        <div className="flex flex-col items-center">
          <img
            src={sponsors[2]?.image_thumb}
            alt="3rd place logo"
            className="mb-2 rounded-lg  w-36 border-4 border-[#347496]"
          />
          <div className="w-56 h-20 bg-[#347496] flex items-center justify-center rounded-lg relative">
            <span className="text-white text-lg font-bold">
              3<sup>rd</sup>
            </span>
            <div className="absolute top-0 right-0 bg-gray-900 text-white px-2 py-0.5 rounded-full text-xs font-medium">
              Score: {sponsors[2]?.overallScore}
            </div>
          </div>
          <div className="mt-2 flex items-center">
            <Link
              href="#"
              className="text-sm font-medium hover:underline"
              prefetch={false}
            >
              {sponsors[2]?.name} 
            </Link>
            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  <button className="ml-2 text-gray-500 hover:text-gray-900 dark:hover:text-gray-100">
                    <InfoIcon className="h-4 w-4" />
                  </button>
                </TooltipTrigger>
                <TooltipContent>
                  <p>This is the 3rd place winner.</p>
                </TooltipContent>
              </Tooltip>
            </TooltipProvider>
          </div>
        </div>
      </div>

      {/* RUNNER-UPs */}
      <Card className="px-6 pb-6 pt-0 w-full mx-0 my-4 bg-slate-300">
        <div className="flex justify-center items-end space-x-4 mt-8">
          <h2 className="text-2xl font-bold mb-4">Honourable Mentions</h2>
        </div>
        <div className="flex justify-center items-start space-x-4 mt-4">
          <div className="flex flex-col items-center relative">
            <img
              src={sponsors[3]?.image_thumb}
              alt="4th place logo"
              className="mb-2 rounded-lg  w-44  border-4 border-[#0077b6]"
            />
            <div className="absolute top-0 right-0 bg-gray-900 text-white px-2 py-0.5 rounded-full text-xs font-medium">
              Score: {sponsors[3]?.overallScore}
            </div>
            <div className="mt-2 flex-col justify-center align-middle items-center">
              4<sup>th</sup> Place
              <Link
                href="#"
                className="text-sm font-medium hover:underline"
                prefetch={false}
              >
                <div className="mt-1 text-sm text-gray-500 dark:text-gray-400">
                  {sponsors[3]?.name}
                </div>
              </Link>
            </div>
          </div>
          <div className="flex flex-col items-center relative">
            <img
              src={sponsors[4]?.image_thumb}
              alt="5th place logo"
              className="mb-2 rounded-lg  w-44 border-4 border-[#0077b6]"
            />
            <div className="absolute top-0 right-0 bg-gray-900 text-white px-2 py-0.5 rounded-full text-xs font-medium">
              Score: {sponsors[4]?.overallScore}
            </div>
            <div className="mt-2 flex-col justify-center align-middle items-center">
              5<sup>th</sup> Place
              <Link
                href="#"
                className="text-sm font-medium hover:underline"
                prefetch={false}
              >
                <div className="mt-1 text-sm text-gray-500 dark:text-gray-400">
                  {sponsors[4]?.name}
                </div>
              </Link>
            </div>
          </div>
          <div className="flex flex-col items-center relative">
            <img
              src={sponsors[5]?.image_thumb}
              alt="6th place logo"
              className="mb-2 rounded-lg w-44 border-4 border-[#0077b6]"
            />
            <div className="absolute top-0 right-0 bg-gray-900 text-white px-2 py-0.5 rounded-full text-xs font-medium">
              Score: {sponsors[5]?.overallScore}
            </div>
            <div className="mt-2 flex-col justify-center align-middle items-center">
              6<sup>th</sup> Place
              <Link
                href="#"
                className="text-sm font-medium hover:underline"
                prefetch={false}
              >
                <div className="mt-1 text-sm text-gray-500 dark:text-gray-400">
                  {sponsors[5]?.name}
                </div>
              </Link>
            </div>
          </div>
          <div className="flex flex-col items-center relative">
            <img
              src={sponsors[6]?.image_thumb}
              alt="7th place logo"
              className="mb-2 rounded-lg w-44 border-4 border-[#0077b6]"
            />
            <div className="absolute top-0 right-0 bg-gray-900 text-white px-2 py-0.5 rounded-full text-xs font-medium">
              Score: {sponsors[6]?.overallScore}
            </div>
            <div className="mt-2 flex-col justify-center align-middle items-center">
              7<sup>th</sup> Place
              <Link
                href="#"
                className="text-sm font-medium hover:underline"
                prefetch={false}
              >
                <div className="mt-1 text-sm text-gray-500 dark:text-gray-400">
                  {sponsors[6]?.name}
                </div>
              </Link>
            </div>
          </div>
          <div className="flex flex-col items-center relative">
            <img
              src={sponsors[7]?.image_thumb}
              alt="8th place logo"
              className="mb-2 rounded-lg w-44 border-4 border-[#0077b6]"
            />
            <div className="absolute top-0 right-0 bg-gray-900 text-white px-2 py-0.5 rounded-full text-xs font-medium">
              Score: {sponsors[7]?.overallScore}
            </div>
            <div className="mt-2 flex-col justify-center align-middle items-center">
              8<sup>th</sup> Place
              <Link
                href="#"
                className="text-sm font-medium hover:underline"
                prefetch={false}
              >
                <div className="mt-1 text-sm text-gray-500 dark:text-gray-400">
                  {sponsors[7]?.name}
                </div>
              </Link>
            </div>
          </div>
          <div className="flex flex-col items-center relative">
            <img
              src={sponsors[8]?.image_thumb}
              alt="9th place logo"
              className="mb-2 rounded-lg w-44 border-4 border-[#0077b6]"
            />
            <div className="absolute top-0 right-0 bg-gray-900 text-white px-2 py-0.5 rounded-full text-xs font-medium">
              Score: {sponsors[8]?.overallScore}
            </div>
            <div className="mt-2 flex-col justify-center align-middle items-center">
              9<sup>th</sup> Place
              <Link
                href="#"
                className="text-sm font-medium hover:underline"
                prefetch={false}
              >
                <div className="mt-1 text-sm text-gray-500 dark:text-gray-400">
                  {sponsors[8]?.name}
                </div>
              </Link>
            </div>
          </div>
          <div className="flex flex-col items-center relative">
            <img
              src={sponsors[9]?.image_thumb}
              alt="10th place logo"
              className="mb-2 rounded-lg w-44 border-4 border-[#0077b6]"
            />
            <div className="absolute top-0 right-0 bg-gray-900 text-white px-2 py-0.5 rounded-full text-xs font-medium">
              Score: {sponsors[9]?.overallScore}
            </div>
            <div className="mt-2 flex-col justify-center align-middle items-center">
              10<sup>th</sup> Place
              <Link
                href="#"
                className="text-sm font-medium hover:underline"
                prefetch={false}
              >
                <div className="mt-1 text-sm text-gray-500 dark:text-gray-400">
                  {sponsors[9]?.name}
                </div>
              </Link>
            </div>
          </div>
        </div>
      </Card>
    </div>
  );
}
