/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/1fVuszaOgd3
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";

import { useState } from "react";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  CardFooter,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { CheckIcon } from "lucide-react";
import { WinnersPodium } from "./winners-podium";
import { WinnersPodiumOverall } from "./winners-podium-overall";

export function WinnersTabBox() {
  const [activeTab, setActiveTab] = useState("Overall");
  return (
    <div className="w-full max-w-screen-lg mx-auto sm:px-4 md:px-8">
      <Tabs value={activeTab} onValueChange={setActiveTab} className="border-b">
        <TabsList className="flex flex-shrink mx-auto">
          <TabsTrigger value={"Overall"}>Overall</TabsTrigger>
          <TabsTrigger value={"Booth"}>Booth</TabsTrigger>
          <TabsTrigger value={"Swag"}>Swag</TabsTrigger>
          <TabsTrigger value={"Sustainable"}>Sustainable</TabsTrigger>
        </TabsList>
        <TabsContent value={"Overall"}>
          <Card className="p-6">
            <CardHeader>
              <CardTitle>Best Overall</CardTitle>
              <CardDescription>
                Sponsor with the top overall Swagathon score based on the
                transparent rating formula.
              </CardDescription>
              <CardContent>
                <WinnersPodiumOverall />
              </CardContent>
            </CardHeader>
          </Card>
        </TabsContent>
        <TabsContent value={"Booth"}>
          <Card className="p-6">
            <CardHeader>
              <CardTitle>Powerful Features</CardTitle>
              <CardDescription>
                Discover the capabilities that set our product apart.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <ul className="space-y-2">
                <li>
                  <h4 className="font-medium">Automation</h4>
                  <p>
                    Automate repetitive tasks and free up your time for more
                    important work.
                  </p>
                </li>
                <li>
                  <h4 className="font-medium">Collaboration</h4>
                  <p>
                    Seamlessly work with your team and share information in
                    real-time.
                  </p>
                </li>
                <li>
                  <h4 className="font-medium">Analytics</h4>
                  <p>
                    Gain valuable insights with our advanced analytics tools.
                  </p>
                </li>
              </ul>
            </CardContent>
          </Card>
        </TabsContent>
        <TabsContent value={"Swag"}>
          <Card className="p-6">
            <CardHeader>
              <CardTitle>Pricing Plans</CardTitle>
              <CardDescription>
                Choose the plan that best fits your needs.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid gap-4 md:grid-cols-2">
                <Card>
                  <CardHeader>
                    <CardTitle>Starter</CardTitle>
                    <CardDescription>$9/month</CardDescription>
                  </CardHeader>
                  <CardContent>
                    <ul className="space-y-2 text-sm">
                      <li>
                        <CheckIcon className="w-4 h-4 mr-2 text-green-500" />5
                        users
                      </li>
                      <li>
                        <CheckIcon className="w-4 h-4 mr-2 text-green-500" />1
                        GB storage
                      </li>
                      <li>
                        <CheckIcon className="w-4 h-4 mr-2 text-green-500" />
                        Basic features
                      </li>
                    </ul>
                  </CardContent>
                  <CardFooter>
                    <Button>Get Started</Button>
                  </CardFooter>
                </Card>
                <Card>
                  <CardHeader>
                    <CardTitle>Pro</CardTitle>
                    <CardDescription>$29/month</CardDescription>
                  </CardHeader>
                  <CardContent>
                    <ul className="space-y-2 text-sm">
                      <li>
                        <CheckIcon className="w-4 h-4 mr-2 text-green-500" />
                        Unlimited users
                      </li>
                      <li>
                        <CheckIcon className="w-4 h-4 mr-2 text-green-500" />
                        50 GB storage
                      </li>
                      <li>
                        <CheckIcon className="w-4 h-4 mr-2 text-green-500" />
                        Advanced features
                      </li>
                    </ul>
                  </CardContent>
                  <CardFooter>
                    <Button>Get Started</Button>
                  </CardFooter>
                </Card>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
        <TabsContent value={"Sustainable"}>
          <Card className="p-6">
            <CardHeader>
              <CardTitle>Get in Touch</CardTitle>
              <CardDescription>
                Have questions or need help? Contact us.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <form className="grid gap-4">
                <div className="grid gap-1">
                  <Label htmlFor="name">Name</Label>
                  <Input id="name" placeholder="Your name" />
                </div>
                <div className="grid gap-1">
                  <Label htmlFor="email">Email</Label>
                  <Input id="email" type="email" placeholder="Your email" />
                </div>
                <div className="grid gap-1">
                  <Label htmlFor="message">Message</Label>
                  <Textarea id="message" placeholder="Your message" rows={4} />
                </div>
                <Button type="submit">Submit</Button>
              </form>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}
