/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/DesaeIegeB8
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
export function WinnerPodium() {
  return (
    <div className="flex justify-center items-end space-x-4 mt-8">
      <div className="flex flex-col items-center">
        <img
          src="/placeholder.svg"
          alt="2nd place logo"
          className="mb-2 rounded-lg bg-[#0077b6] w-44"
        />
        <div className="w-60 h-36 bg-[#0077b6] flex items-center justify-center rounded-lg">
          <span className="text-white text-lg font-bold">
            2<sup>nd</sup>
          </span>
        </div>
        <div className="mt-2">
          <span className="text-sm font-medium">Winner name</span>
        </div>
      </div>
      <div className="flex flex-col items-center">
        <img
          src="/placeholder.svg"
          alt="1st place logo"
          className="mb-2 rounded-lg bg-[#023e8a] w-56"
        />
        <div className="w-64 h-48 bg-[#023e8a] flex items-center justify-center rounded-lg">
          <span className="text-white text-lg font-bold">
            1<sup>st</sup>
          </span>
        </div>
        <div className="mt-2">
          <span className="text-sm font-medium">Winner name</span>
        </div>
      </div>
      <div className="flex flex-col items-center">
        <img
          src="/placeholder.svg"
          alt="3rd place logo"
          className="mb-2 rounded-lg bg-[#0077b6] w-36"
        />
        <div className="w-56 h-20 bg-[#347496] flex items-center justify-center rounded-lg">
          <span className="text-white text-lg font-bold">
            3<sup>rd</sup>
          </span>
        </div>
        <div className="mt-2">
          <span className="text-sm font-medium">Winner name</span>
        </div>
      </div>
    </div>
  );
}
