/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/sDPZFhF1juk
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { SunMoonIcon } from "lucide-react"

export function ThemeToggle() {
  const [theme, setTheme] = useState("light")
  const toggleTheme = () => {
    setTheme(theme === "light" ? "dark" : "light")
  }
  useEffect(() => {
    document.documentElement.classList.remove("light", "dark")
    document.documentElement.classList.add(theme)
  }, [theme])
  return (
    <Button variant="outline" onClick={toggleTheme} className="flex items-center gap-2">
      <SunMoonIcon className="h-5 w-5" />
      <span>{theme === "light" ? "Light" : "Dark"}</span>
    </Button>
  )
}

